server:
  port: 8080

# Actuator settings.
management:
  endpoints:
    web:
      exposure:
        include:
        #- beans
        - health
        - info
        - metrics
  endpoint:
    health:
      show-details: always